//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog : BaseModel<ErrorLog>
    {
        public int Id { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public string StackTrace { get; set; }
        public string Message { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public string Object { get; set; }
        public string Function { get; set; }
        public Nullable<int> Line { get; set; }
        public string HResult { get; set; }
        public string InnerMessage { get; set; }
        public bool Important { get; set; }
        public string Type { get; set; }
    }
}
