//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleGalleryImage : BaseModel<ModuleGalleryImage>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleGalleryImage()
        {
            this.ModuleGalleryImageLinks = new HashSet<ModuleGalleryImageLink>();
        }
    
        public int Id { get; set; }
        public string Image { get; set; }
        public int ModuleGalleryId { get; set; }
        public int Position { get; set; }
    
        public virtual ModuleGallery ModuleGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleGalleryImageLink> ModuleGalleryImageLinks { get; set; }
    }
}
