//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePromo : BaseModel<ModulePromo>
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Text { get; set; }
        public string ButtonText { get; set; }
        public string ButtonLink { get; set; }
        public bool ImageRight { get; set; }
        public bool TitleTop { get; set; }
    }
}
