//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleProfileCardsCard : BaseModel<ModuleProfileCardsCard>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleProfileCardsCard()
        {
            this.ModuleProfileCardsCardLinks = new HashSet<ModuleProfileCardsCardLink>();
        }
    
        public int Id { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string TwitchUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string YouTubeUrl { get; set; }
        public int Position { get; set; }
        public int ModuleProfileCardsId { get; set; }
    
        public virtual ModuleProfileCards ModuleProfileCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleProfileCardsCardLink> ModuleProfileCardsCardLinks { get; set; }
    }
}
