//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleSimpleCardsCard : BaseModel<ModuleSimpleCardsCard>
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public int Position { get; set; }
        public int ModuleSimpleCardsId { get; set; }
    
        public virtual ModuleSimpleCards ModuleSimpleCards { get; set; }
    }
}
