//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleBoxesBox : BaseModel<ModuleBoxesBox>
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string Color { get; set; }
        public string Text { get; set; }
        public int Position { get; set; }
        public int ModuleBoxesId { get; set; }
        public string Url { get; set; }
    
        public virtual ModuleBoxes ModuleBoxes { get; set; }
    }
}
