//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleProfileCardsCardLink : BaseModel<ModuleProfileCardsCardLink>
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public int Position { get; set; }
        public int ModuleProfileCardsCardId { get; set; }
    
        public virtual ModuleProfileCardsCard ModuleProfileCardsCard { get; set; }
    }
}
