//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageModule : BaseModel<PageModule>
    {
        public int Id { get; set; }
        public int ModuleTypeId { get; set; }
        public int PageId { get; set; }
        public int ModuleId { get; set; }
        public int Position { get; set; }
        public bool Theme { get; set; }
        public bool TransparentBackground { get; set; }
        public PageModuleStates State { get; set; }
        public string Title { get; set; }
        public bool BlueTitle { get; set; }
        public bool LootBox { get; set; }
        public int LootBoxTop { get; set; }
        public int LootBoxLeft { get; set; }
    
        public virtual ModuleType ModuleType { get; set; }
        public virtual Page Page { get; set; }
    }
}
