//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTG.Logic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSettings : BaseModel<SiteSettings>
    {
        public int Id { get; set; }
        public string MetaSiteTitle { get; set; }
        public string MetaSiteDescription { get; set; }
        public string MetaFaviconImageUrl { get; set; }
        public string MetaOgLocale { get; set; }
        public string MetaOgTitle { get; set; }
        public string MetaOgDescription { get; set; }
        public string MetaOgImageType { get; set; }
        public Nullable<int> MetaOgImageWidth { get; set; }
        public Nullable<int> MetaOgImageHeight { get; set; }
        public string MetaOgUrl { get; set; }
        public string MetaOgSiteName { get; set; }
        public string MetaOgType { get; set; }
        public string HeaderHomeImageUrl { get; set; }
        public string FooterHomeImageUrlLight { get; set; }
        public string FooterHomeImageUrlDark { get; set; }
        public string BlogUrl { get; set; }
        public string ForumUrl { get; set; }
        public string ShopUrl { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string YouTubeUrl { get; set; }
        public string TwitchUrl { get; set; }
        public string MetaTwitterCard { get; set; }
        public string MetaTwitterSite { get; set; }
        public string MetaTwitterTitle { get; set; }
        public string MetaTwitterDescription { get; set; }
        public string RedditUrl { get; set; }
        public string LootBoxImageUrl { get; set; }
        public string LootBoxPopupTitle { get; set; }
        public string LootBoxPopupText { get; set; }
        public string MetaOgImageUrl { get; set; }
        public string MetaTwitterImageUrl { get; set; }
        public string LoadingImageUrl { get; set; }
        public string ErrorImage401Url { get; set; }
        public string ErrorImage403Url { get; set; }
        public string ErrorImage404Url { get; set; }
        public string ErrorImage500Url { get; set; }
        public string ErrorImage503Url { get; set; }
        public string ErrorImageIconTopUrl { get; set; }
    }
}
