CREATE TABLE [dbo].[SiteSettings] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
	[MetaSiteTitle]     NVARCHAR (50) NULL,
	[MetaSiteDescription]     NVARCHAR (MAX) NULL,
	[MetaFaviconImageUrl]		NVARCHAR(MAX) NULL,
	[MetaOgLocale]     NVARCHAR (10) NULL,
	[MetaOgTitle]     NVARCHAR (50) NULL,
	[MetaOgDescription]     NVARCHAR (MAX) NULL,
	[MetaOgImageUrl]     NVARCHAR (MAX) NULL,
	[MetaOgImageType]     NVARCHAR (20) NULL,
	[MetaOgImageWidth]     INT NULL,
	[MetaOgImageHeight]     INT NULL,
	[MetaOgUrl]     NVARCHAR (MAX) NULL,
	[MetaOgSiteName]     NVARCHAR (50) NULL,
	[MetaOgType]     NVARCHAR (20) NULL,
	[MetaTwitterCard]     NVARCHAR (20) NULL,
	[MetaTwitterSite]     NVARCHAR (50) NULL,
	[MetaTwitterTitle]     NVARCHAR (50) NULL,
	[MetaTwitterDescription]     NVARCHAR (MAX) NULL,
	[MetaTwitterImageUrl]     NVARCHAR (MAX) NULL,
	[HeaderHomeImageUrl]     NVARCHAR (MAX) NULL,
	[FooterHomeImageUrlLight]     NVARCHAR (MAX) NULL,
	[FooterHomeImageUrlDark]     NVARCHAR (MAX) NULL,
	[LoadingImageUrl]     NVARCHAR (MAX) NULL,
	[ErrorImage401Url]     NVARCHAR (MAX) NULL,
	[ErrorImage403Url]     NVARCHAR (MAX) NULL,
	[ErrorImage404Url]     NVARCHAR (MAX) NULL,
	[ErrorImage500Url]     NVARCHAR (MAX) NULL,
	[ErrorImage503Url]     NVARCHAR (MAX) NULL,
	[ErrorImageIconTopUrl]     NVARCHAR (MAX) NULL,
	[LootBoxImageUrl]     NVARCHAR (MAX) NULL,
	[LootBoxPopupTitle]     NVARCHAR (50) NULL,
	[LootBoxPopupText]     NVARCHAR (MAX) NULL,
    [BlogUrl]     NVARCHAR (MAX) NULL,
    [ForumUrl]     NVARCHAR (MAX) NULL,
	[ShopUrl]     NVARCHAR (MAX) NULL,
	[FacebookUrl]     NVARCHAR (MAX) NULL,
	[TwitterUrl]     NVARCHAR (MAX) NULL,
	[RedditUrl]     NVARCHAR (MAX) NULL, 
	[YouTubeUrl]     NVARCHAR (MAX) NULL,
	[TwitchUrl]     NVARCHAR (MAX) NULL, 
    CONSTRAINT [PK_SiteSettings] PRIMARY KEY CLUSTERED ([Id] ASC),
);
